#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/ba5f1d9e-9f6c-4660-80e5-033c2569f744 # baseUri: https://mocksvc.mulesoft.com/mocks/6fa62240-f699-4df0-846c-90c540a3813f # 
title: Global Weather API
version: v1.0
types:
  citiesByCountryResponse: 
      type: object
      properties:
        country: 
          required: false
          description: Country of interest
          type: string
        cities: 
          required: false
          description: List of Cities retrieved for a given country
          type: city[]
  city: 
    type: object
    properties: 
      cityName: 
        required: false
        description: A city
        type: string

  weatherResponse:
    displayName: weather Information for a given city
    type: object
    properties:
      location:
        required: false
        displayName: Location
        description: Location for which weather information is being retrieved
        type: string
      time:
        required: false
        displayName: Time
        description: Time weather report was retrieved
        type: string
      wind:
        required: false
        displayName: Wind
        description: Wind speed, in km/sec
        type: string
      visibility:
        required: false
        displayName: Visibility
        description: Visibility, in km
        type: string
      skyConditions: 
        required: false
        displayName: Sky Conditions
        description: Sky Conditions for the day
        type: string
      temperature:
        required: false
        displayName: Temperature
        description: Temperature, in Celcius
        type: string
      dewPoint: 
        required: false
        displayName: Dew Point
        description: Dew Point
        type: string
      relativeHumidity:
        required: false
        displayName: Humidity
        description: Humidity, %
        type: string
      status:
        required: false
        displayName: Status
        description: status
        type: string

/countries:
  description: Countries collection resource

  /{country_id}/cities:
    description: Countrty instance resource allowing to retrieve cities of a country given by country_id.
    get:
      displayName: get
      description: Get a list of cities for a given country
      responses:
        200:
          body:
            application/json:
              displayName: Get Cities By Country Response
              description: Get a list of cities for a given country 
              type: citiesByCountryResponse
              example: !include exchange_modules/f7796a83-34e4-48d9-bcb9-549c506676ce/global-weather-cities-example/1.0.3/global-weather-cities-example.raml
        400:
          body:
            application/json:
              displayName: Request Invalid
              description: Request Invalid
        404:
          body:
            application/json:
              displayName: Resource not Found
              description: Resource not Found
        405:
          body:
            application/json:
              displayName: Method Not Allowed
              description: Method Not Allowed
        500:
          body:
            application/json:
              displayName: Internal server error
              description: Internal server error
/weather:
  description: Resource allowing access to weather details for a location
  get:
    displayName: get
    description: Access current weather data for any location, given by city name, or city and country name
    queryParameters:
      city:
        required: true 
        type: string 
      country:
        required: false
        type: string 
    responses:
      200:
        body:
          application/json:
            displayName: Get Weather Response
            description: Get weather information for a given city response
            type: weatherResponse
            example: !include exchange_modules/f7796a83-34e4-48d9-bcb9-549c506676ce/global-weather-example/1.0.0/global-weather-example.raml
      400:
         body:
           application/json:
             displayName: Request Invalid
             description: Request Invalid
      404:
        body:
          application/json:
            displayName: Resource was not Found
            description: Resource was not Found
      405:
        body:
          application/json:
            displayName: Method Not Allowed
            description: Method Not Allowed
      
      500:
        body:
          application/json:
            displayName: Internal Server Error
            description: Internal Server Error

    body: {}

